server:
  port: 8181
spring:
  application:
    name: simple-service
  datasource:
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1qaz!QAZ
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.org.prac.simple.entity  

#日志
logging:
  config: classpath:log/logback.xml
  path: D://logs/simple-service